# Generated by Django 4.2.20 on 2025-04-17 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_devicetype"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="类型名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
            ],
            options={
                "verbose_name": "技能类型",
                "verbose_name_plural": "技能类型",
                "ordering": ["name"],
            },
        ),
    ]
