# Generated by Django 4.2.20 on 2025-04-19 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_skill_skilltype_update"),
    ]

    operations = [
        migrations.AddField(
            model_name="userreward",
            name="issuance_type",
            field=models.CharField(
                choices=[("manual", "手动发放"), ("automatic", "自动发放")],
                default="manual",
                max_length=10,
                verbose_name="发放类型",
            ),
        ),
        migrations.AddField(
            model_name="userreward",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="issued_rewards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发放人",
            ),
        ),
    ]
