# Generated by Django 4.2.20 on 2025-04-19 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_userreward_issuance_type_userreward_issued_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(max_length=100, verbose_name="兑换项目名称"),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="兑换数量"),
                ),
                ("points_spent", models.IntegerField(verbose_name="消耗积分")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "处理中"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="兑换时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "积分兑换记录",
                "verbose_name_plural": "积分兑换记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
