# Generated by Django 4.2.20 on 2025-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_exchangerecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="additional_info",
            field=models.TextField(blank=True, null=True, verbose_name="附加信息"),
        ),
        migrations.AlterField(
            model_name="device",
            name="browser",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="浏览器"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="browser_version",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="浏览器版本"
            ),
        ),
        migrations.AlterField(
            model_name="device",
            name="screen_resolution",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="屏幕分辨率"
            ),
        ),
    ]
