# Generated by Django 4.2.20 on 2025-04-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestCaseStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.PositiveIntegerField(verbose_name="步骤编号")),
                ("action", models.TextField(verbose_name="操作步骤")),
                (
                    "expected_result",
                    models.TextField(blank=True, verbose_name="预期结果"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="备注")),
            ],
        ),
        migrations.CreateModel(
            name="TestCaseVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField(verbose_name="版本号")),
                ("title", models.CharField(max_length=255, verbose_name="用例标题")),
                (
                    "precondition",
                    models.TextField(blank=True, null=True, verbose_name="前置条件"),
                ),
                (
                    "priority",
                    models.CharField(blank=True, max_length=20, verbose_name="优先级"),
                ),
                (
                    "case_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="用例类型"
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="测试方法"
                    ),
                ),
                (
                    "steps_data",
                    models.JSONField(
                        blank=True, default=list, verbose_name="步骤数据 (JSON)"
                    ),
                ),
                (
                    "change_description",
                    models.TextField(blank=True, verbose_name="版本变更说明"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="版本创建时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="是否为活动版本"
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_testcase_versions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="版本创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例版本",
                "verbose_name_plural": "测试用例版本",
                "ordering": ["test_case", "-version_number"],
            },
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="case_type",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="method",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="preconditions",
        ),
        migrations.RemoveField(
            model_name="testcase",
            name="priority",
        ),
        migrations.DeleteModel(
            name="TestStep",
        ),
        migrations.AddField(
            model_name="testcaseversion",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="testcases.testcase",
                verbose_name="原始测试用例",
            ),
        ),
        migrations.AddField(
            model_name="testcasestep",
            name="test_case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="testcases.testcase",
                verbose_name="所属用例",
            ),
        ),
        migrations.AddField(
            model_name="testcase",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="testcases.testcaseversion",
                verbose_name="当前活动版本",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcaseversion",
            unique_together={("test_case", "version_number")},
        ),
    ]
