# Generated by Django 4.2.20 on 2025-04-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0002_testcasestep_testcaseversion_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testcasestep",
            options={
                "ordering": ["version", "step_number"],
                "verbose_name": "测试步骤",
                "verbose_name_plural": "测试步骤",
            },
        ),
        migrations.AddField(
            model_name="testcasestep",
            name="version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="steps",
                to="testcases.testcaseversion",
                verbose_name="所属版本",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcasestep",
            unique_together={("version", "step_number")},
        ),
        migrations.RemoveField(
            model_name="testcasestep",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="testcasestep",
            name="test_case",
        ),
    ]
