# Generated by Django 4.2.20 on 2025-04-23 23:23

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0003_alter_testcasestep_options_testcasestep_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testcaseversion",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=768, null=True, verbose_name="语义向量"
            ),
        ),
        migrations.AddField(
            model_name="testcaseversion",
            name="embedding_model_version",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="嵌入模型版本"
            ),
        ),
    ]
