# Generated by Django 4.2.20 on 2025-04-23 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("testcases", "0003_alter_testcasestep_options_testcasestep_version_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PotentialDuplicatePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="计算得到的嵌入向量间的相似度分数（例如余弦相似度）。",
                        verbose_name="相似度分数",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待处理"),
                            ("confirmed", "已确认重复"),
                            ("ignored", "非重复"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="检测时间"),
                ),
                (
                    "version_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_pairs_a",
                        to="testcases.testcaseversion",
                        verbose_name="测试用例版本 A",
                    ),
                ),
                (
                    "version_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duplicate_pairs_b",
                        to="testcases.testcaseversion",
                        verbose_name="测试用例版本 B",
                    ),
                ),
            ],
            options={
                "verbose_name": "潜在重复用例对",
                "verbose_name_plural": "潜在重复用例对",
                "ordering": ["-similarity_score", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="potentialduplicatepair",
            constraint=models.CheckConstraint(
                check=models.Q(("version_a", models.F("version_b")), _negated=True),
                name="prevent_self_pairing",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="potentialduplicatepair",
            unique_together={("version_a", "version_b")},
        ),
    ]
