# Generated by Django 4.2.20 on 2025-04-19 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="项目名称")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="项目代号"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="项目描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "规划中"),
                            ("in_progress", "进行中"),
                            ("suspended", "已暂停"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="项目状态",
                    ),
                ),
                (
                    "priority",
                    models.SmallIntegerField(
                        choices=[(1, "低"), (2, "中"), (3, "高"), (4, "紧急")],
                        default=2,
                        verbose_name="优先级",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "test_case_count",
                    models.IntegerField(default=0, verbose_name="测试用例数量"),
                ),
                ("bug_count", models.IntegerField(default=0, verbose_name="缺陷数量")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_projects",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="项目经理",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目",
                "verbose_name_plural": "项目",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="标签名称"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#409EFF", max_length=20, verbose_name="标签颜色"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="标签描述"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "项目标签",
                "verbose_name_plural": "项目标签",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="文档标题")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("requirement", "需求文档"),
                            ("design", "设计文档"),
                            ("test_plan", "测试计划"),
                            ("api_doc", "API文档"),
                            ("user_manual", "用户手册"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="文档描述")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="project_documents/%Y/%m/",
                        verbose_name="文档文件",
                    ),
                ),
                ("url", models.URLField(blank=True, verbose_name="文档链接")),
                ("content", models.TextField(blank=True, verbose_name="文档内容")),
                (
                    "version",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="文档版本"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目文档",
                "verbose_name_plural": "项目文档",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="projects",
                to="projects.projecttag",
                verbose_name="项目标签",
            ),
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="里程碑名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "计划中"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("delayed", "已延期"),
                        ],
                        default="planned",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="开始日期")),
                ("due_date", models.DateField(verbose_name="截止日期")),
                (
                    "completed_date",
                    models.DateField(blank=True, null=True, verbose_name="完成日期"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "里程碑",
                "verbose_name_plural": "里程碑",
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="ProjectMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("project_manager", "项目经理"),
                            ("test_manager", "测试经理"),
                            ("tester", "测试人员"),
                            ("developer", "开发人员"),
                            ("observer", "观察者"),
                        ],
                        max_length=20,
                        verbose_name="角色",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否活跃"),
                ),
                (
                    "can_manage_members",
                    models.BooleanField(default=False, verbose_name="可管理成员"),
                ),
                (
                    "can_manage_test_cases",
                    models.BooleanField(default=False, verbose_name="可管理测试用例"),
                ),
                (
                    "can_manage_executions",
                    models.BooleanField(default=False, verbose_name="可管理测试执行"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目成员",
                "verbose_name_plural": "项目成员",
                "unique_together": {("project", "user")},
            },
        ),
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="环境名称")),
                ("description", models.TextField(blank=True, verbose_name="环境描述")),
                ("server_url", models.URLField(blank=True, verbose_name="服务器地址")),
                (
                    "api_base_url",
                    models.URLField(blank=True, verbose_name="API基础地址"),
                ),
                (
                    "database_config",
                    models.JSONField(blank=True, null=True, verbose_name="数据库配置"),
                ),
                (
                    "env_variables",
                    models.JSONField(blank=True, null=True, verbose_name="环境变量"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否可用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="environments",
                        to="projects.project",
                        verbose_name="项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试环境",
                "verbose_name_plural": "测试环境",
                "unique_together": {("project", "name")},
            },
        ),
    ]
