# Generated by Django 4.2.20 on 2025-04-21 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("testcases", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="计划名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="开始日期"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="结束日期"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "规划中"),
                            ("ready", "准备就绪"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("archived", "已归档"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_test_plans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_plans",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试计划",
                "verbose_name_plural": "测试计划",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestPlanCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_run", "未执行"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("blocked", "阻塞"),
                            ("skipped", "跳过"),
                        ],
                        default="not_run",
                        max_length=20,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="用例在计划中的执行顺序",
                        verbose_name="顺序",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_plan_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="指派给",
                    ),
                ),
                (
                    "test_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_associations",
                        to="testcases.testcase",
                        verbose_name="测试用例",
                    ),
                ),
                (
                    "test_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_cases",
                        to="executions.testplan",
                        verbose_name="所属测试计划",
                    ),
                ),
            ],
            options={
                "verbose_name": "计划用例关联",
                "verbose_name_plural": "计划用例关联",
                "ordering": ["order", "id"],
                "unique_together": {("test_plan", "test_case")},
            },
        ),
    ]
