# Generated by Django 4.2.20 on 2025-04-21 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("executions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("untested", "未测试"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("skipped", "跳过"),
                            ("blocked", "阻塞"),
                        ],
                        db_index=True,
                        default="untested",
                        max_length=10,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="执行完成时间"
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="执行耗时"
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="实际结果/备注"
                    ),
                ),
                (
                    "bug_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="关联缺陷ID",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试结果",
                "verbose_name_plural": "测试结果",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="TestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="执行轮次名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="执行描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "未开始"),
                            ("in_progress", "进行中"),
                            ("completed", "已完成"),
                            ("blocked", "已阻塞"),
                            ("aborted", "已中止"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际开始时间"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="实际结束时间"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_test_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人/执行人",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="test_runs",
                        to="projects.environment",
                        verbose_name="测试环境",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_runs",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试执行轮次",
                "verbose_name_plural": "测试执行轮次",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="testplan",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否激活"),
        ),
        migrations.AlterField(
            model_name="testplan",
            name="status",
            field=models.CharField(
                choices=[
                    ("planning", "规划中"),
                    ("ready", "准备就绪"),
                    ("archived", "已归档"),
                ],
                default="planning",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.DeleteModel(
            name="TestPlanCase",
        ),
        migrations.AddField(
            model_name="testrun",
            name="test_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_runs",
                to="executions.testplan",
                verbose_name="所属测试计划",
            ),
        ),
        migrations.AddField(
            model_name="testrun",
            name="testcases",
            field=models.ManyToManyField(
                blank=True,
                related_name="test_runs_m2m",
                through="executions.TestResult",
                to="testcases.testcase",
                verbose_name="包含的测试用例",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="test_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="executions.testrun",
                verbose_name="所属执行轮次",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="testcase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="testcases.testcase",
                verbose_name="测试用例",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together={("test_run", "testcase")},
        ),
    ]
