# Generated by Django 4.2.20 on 2025-04-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0001_initial"),
        ("executions", "0002_testresult_testrun_testplan_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testplan",
            name="plan_cases",
            field=models.ManyToManyField(
                blank=True,
                related_name="test_plans",
                to="testcases.testcase",
                verbose_name="包含的测试用例",
            ),
        ),
    ]
