# Generated by Django 4.2.20 on 2025-04-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testcases", "0002_testcasestep_testcaseversion_and_more"),
        ("executions", "0003_testplan_plan_cases"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="testplan",
            name="plan_cases",
        ),
        migrations.RemoveField(
            model_name="testrun",
            name="testcases",
        ),
        migrations.AddField(
            model_name="testplan",
            name="plan_case_versions",
            field=models.ManyToManyField(
                blank=True,
                related_name="test_plans",
                to="testcases.testcaseversion",
                verbose_name="包含的测试用例版本",
            ),
        ),
        migrations.AddField(
            model_name="testresult",
            name="testcase_version",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="testcases.testcaseversion",
                verbose_name="测试用例版本",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testresult",
            unique_together={("test_run", "testcase_version")},
        ),
        migrations.RemoveField(
            model_name="testresult",
            name="testcase",
        ),
    ]
